CREATE DATABASE PRADEEP
USE PRADEEP
CREATE TABLE EMPLOYEE_DETAIL_1 (Emp_Id INT, Emp_Name VARCHAR(20), Emp_Salary INT , Emp_City VARCHAR(25))
CREATE TABLE EMPLOYEE_DETAIL_2 (Emp_Id INT, Emp_Name VARCHAR(20), Emp_Salary INT , Emp_City VARCHAR(25))

INSERT INTO EMPLOYEE_DETAIL_1 (Emp_Id,Emp_Name,Emp_Salary,Emp_city) VALUES (201,'SANJAY',25000,'DELHI')
INSERT INTO EMPLOYEE_DETAIL_1 VALUES (202,'AJAY',45000,'DELHI') 
INSERT INTO EMPLOYEE_DETAIL_1 VALUES (203,'SAKET',30000,'ALIGARH')


INSERT INTO EMPLOYEE_DETAIL_2 VALUES (203,'SAKET',30000,'ALIGARH')
INSERT INTO EMPLOYEE_DETAIL_2 VALUES (204,'SAURABH',40000,'DELHI')
INSERT INTO EMPLOYEE_DETAIL_2 VALUES (205,'RAM',30000,'KERALA')
INSERT INTO EMPLOYEE_DETAIL_2 VALUES (201,'SANJAY',25000,'DELHI')

select * from EMPLOYEE_DETAIL_1
select * from EMPLOYEE_DETAIL_2

SELECT * FROM EMPLOYEE_DETAIL_1 UNION SELECT * FROM EMPLOYEE_DETAIL_2
SELECT * FROM EMPLOYEE_DETAIL_1 INTERSECT SELECT * FROM EMPLOYEE_DETAIL_2
SELECT * FROM EMPLOYEE_DETAIL_1 UNION ALL SELECT * FROM EMPLOYEE_DETAIL_2
SELECT * FROM EMPLOYEE_DETAIL_1 MINUS SELECT * FROM EMPLOYEE_DETAIL_2;


SELECT * FROM EMPLOYEE_DETAIL_1  GROUP BY Emp_Id HAVING (COUNT(Emp_Id)>1)

SELECT * FROM EMPLOYEE_DETAIL_1 a,EMPLOYEE_DETAIL_2 b WHERE a.Emp_Id=b.Emp_Id